owner: TazimanTK
repo: Upptime

sites:
  - name: MainPage (1)
    url: https://tazimantk.freedynamicdns.org/
  - name: MainPage (2)
    url: https://tazimantk.publicvm.com/
  - name: Upptime
    url: https://upptime.tazimantk.publicvm.com/
  - name: MainPage (3)
    url: https://tazimantk.accesscam.org/
  - name: MainPage (4)
    url: https://tazimantk.camdvr.org/
  - name: MainPage (5)
    url: https://tazimantk.casacam.net/
  - name: Invidious
    url: https://invidious.tazimantk.0000004.xyz/
  - name: Instances-API (Invidious)
    url: https://instances.invidious.tazimantk.0000004.xyz/
  - name: Cobalt
    url: https://cobalt.tazimantk.0000004.xyz/
  - name: Cobalt-API
    url: https://api.cobalt.tazimantk.0000004.xyz/
  - name: Upptime11
    url: https://upptime.tazimantk.accesscam.org/
  - name: Farside
    url: https://farside.tazimantk.accesscam.org/
  - name: Pastewin
    url: https://pastewin.tazimantk.accesscam.org/
  - name: Kittygram
    url: https://kittygram.tazimantk.accesscam.org/
  - name: Patchy
    url: https://patchy.tazimantk.accesscam.org/
  - name: LibreX
    url: https://librex.tazimantk.camdvr.org/
  - name: LibreY
    url: https://librey.tazimantk.camdvr.org/
  - name: SearXNG
    url: https://searxng.tazimantk.camdvr.org/
  - name: 015
    url: https://015.tazimantk.camdvr.org/

status-website:
  cname: upptime.tazimantk.publicvm.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: TazimanTK Web Status
  introTitle: "**TazimanTK's Services** Status"
  introMessage: This site monitors the operational status of each service 24 hours a day.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/TazimanTK/Upptime

assignees:
  - TazimanTK

i18n:
  activeIncidents: 進行中のインシデント
  allSystemsOperational: すべてのシステムは正常に稼働しています
  incidentReport: インシデントレポート
  incidentsOnThisDay: この日のインシデント
  live: ライブ
  ongoing: 進行中
  pageTitle: TazimanTK Status
  resolved: 解決済み
  scheduledMaintenance: メンテナンス予定
  status:
    down: ダウン
    up: 稼働中
    degraded: パフォーマンス低下

commitMessages:
  readmeContent: ":pencil: Update summary in README [skip ci]"
  summaryJson: ":card_file_box: Update status summary [skip ci]"
  statusChange: "$EMOJI $SITE_NAME is $STATUS"
  commitAuthorName: Upptime Bot
  commitAuthorEmail: upptime-bot@example.com
